create table if not exists public.client_error_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null,
  message text not null,
  stack text,
  page text,
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.client_error_logs enable row level security;

revoke all on table public.client_error_logs from anon, authenticated;

create index if not exists client_error_logs_created_at_idx
  on public.client_error_logs (created_at desc);

create index if not exists client_error_logs_user_id_created_at_idx
  on public.client_error_logs (user_id, created_at desc);

create or replace function public.report_client_error(
  p_kind text,
  p_message text,
  p_stack text default null,
  p_page text default null,
  p_context jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if coalesce(length(trim(p_message)), 0) = 0 or length(p_message) > 700 then
    raise exception 'INVALID_ERROR_MESSAGE';
  end if;

  if (
    select count(*)
    from public.client_error_logs
    where user_id = v_user_id
      and created_at > now() - interval '1 hour'
  ) >= 20 then
    return;
  end if;

  delete from public.client_error_logs
  where created_at < now() - interval '90 days';

  insert into public.client_error_logs (user_id, kind, message, stack, page, context)
  values (
    v_user_id,
    left(coalesce(nullif(trim(p_kind), ''), 'client_error'), 40),
    left(trim(p_message), 700),
    nullif(left(coalesce(p_stack, ''), 1800), ''),
    nullif(left(coalesce(p_page, ''), 300), ''),
    case when jsonb_typeof(coalesce(p_context, '{}'::jsonb)) = 'object'
      then coalesce(p_context, '{}'::jsonb)
      else '{}'::jsonb
    end
  );
end;
$$;

revoke all on function public.report_client_error(text, text, text, text, jsonb) from public, anon;
grant execute on function public.report_client_error(text, text, text, text, jsonb) to authenticated;

create or replace function public.owner_list_client_errors(p_limit integer default 20)
returns table (
  id bigint,
  user_id uuid,
  display_name text,
  kind text,
  message text,
  page text,
  context jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not exists (
    select 1
    from public.profiles
    where profiles.user_id = auth.uid()
      and profiles.role = 'owner'
  ) then
    raise exception 'ACCESS_DENIED';
  end if;

  return query
  select
    errors.id,
    errors.user_id,
    coalesce(nullif(trim(profiles.display_name), ''), 'Сотрудник') as display_name,
    errors.kind,
    errors.message,
    errors.page,
    errors.context,
    errors.created_at
  from public.client_error_logs errors
  left join public.profiles on profiles.user_id = errors.user_id
  order by errors.created_at desc
  limit least(greatest(coalesce(p_limit, 20), 1), 100);
end;
$$;

revoke all on function public.owner_list_client_errors(integer) from public, anon;
grant execute on function public.owner_list_client_errors(integer) to authenticated;
