-- Planned vacation codes become an irreversible balance deduction after the leave ends.
begin;

alter table public.vacation_balance_snapshots
  drop constraint if exists vacation_balance_snapshots_balance_days_check;
alter table public.vacation_balance_snapshots
  drop constraint if exists vacation_balance_snapshots_balance_days_range;
alter table public.vacation_balance_snapshots
  add constraint vacation_balance_snapshots_balance_days_range
  check (balance_days between -999 and 999);

create table if not exists public.vacation_balance_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  start_date date not null,
  end_date date not null,
  charged_days integer not null check (charged_days between 1 and 366),
  status text not null default 'planned' check (status in ('planned', 'finalized')),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date >= start_date)
);

create index if not exists vacation_balance_events_user_status_end_idx
  on public.vacation_balance_events (user_id, status, end_date);

alter table public.vacation_balance_events enable row level security;

drop policy if exists vacation_balance_events_select_own on public.vacation_balance_events;
create policy vacation_balance_events_select_own
on public.vacation_balance_events for select
to authenticated
using (user_id = auth.uid());

revoke all on table public.vacation_balance_events from public, anon;
grant select on table public.vacation_balance_events to authenticated;

create or replace function public.finalize_due_vacation_balance_events(p_user_id uuid default null)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_today date := (timezone('Europe/Moscow', now()))::date;
  v_snapshot public.vacation_balance_snapshots;
  v_deduction numeric;
  v_months integer;
  v_finalized integer := 0;
  v_affected integer := 0;
begin
  for v_snapshot in
    select snapshot.*
    from public.vacation_balance_snapshots snapshot
    where p_user_id is null or snapshot.user_id = p_user_id
    order by snapshot.user_id
    for update
  loop
    select coalesce(sum(event.charged_days), 0)
    into v_deduction
    from public.vacation_balance_events event
    where event.user_id = v_snapshot.user_id
      and event.status = 'planned'
      and event.end_date < v_today;

    if v_deduction <= 0 then continue; end if;

    v_months := greatest(
      0,
      (extract(year from v_today)::integer - extract(year from v_snapshot.as_of_date)::integer) * 12
      + extract(month from v_today)::integer - extract(month from v_snapshot.as_of_date)::integer
    );

    update public.vacation_balance_snapshots
    set balance_days = greatest(
          -999,
          least(999, round(balance_days + v_months * (annual_days / 12) - v_deduction, 2))
        ),
        as_of_date = v_today,
        updated_at = now()
    where user_id = v_snapshot.user_id;

    update public.vacation_balance_events
    set status = 'finalized',
        finalized_at = now(),
        updated_at = now()
    where user_id = v_snapshot.user_id
      and status = 'planned'
      and end_date < v_today;

    get diagnostics v_affected = row_count;
    v_finalized := v_finalized + v_affected;
  end loop;

  return v_finalized;
end;
$$;

create or replace function public.sync_user_vacation_balance_events(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_as_of_date date;
  v_today date := (timezone('Europe/Moscow', now()))::date;
begin
  if p_user_id is null then return; end if;

  perform public.finalize_due_vacation_balance_events(p_user_id);

  select snapshot.as_of_date
  into v_as_of_date
  from public.vacation_balance_snapshots snapshot
  where snapshot.user_id = p_user_id;

  delete from public.vacation_balance_events
  where user_id = p_user_id and status = 'planned';

  if v_as_of_date is null then return; end if;

  insert into public.vacation_balance_events (
    user_id,
    start_date,
    end_date,
    charged_days,
    status,
    created_at,
    updated_at
  )
  with calendar_dates as (
    select
      make_date(sheet.year, sheet.month + 1, 1) + (leave_item.ordinality::integer - 1) as vacation_date,
      lower(btrim(leave_item.value)) in ('vacation', 'vac_paid', 'о', 'от') as is_vacation,
      coalesce(
        (sheet.payload -> 'isHoliday' ->> (leave_item.ordinality::integer - 1))::boolean,
        false
      ) as is_holiday
    from public.timesheets sheet
    cross join lateral jsonb_array_elements_text(
      coalesce(sheet.payload -> 'leaveType', '[]'::jsonb)
    ) with ordinality as leave_item(value, ordinality)
    where sheet.user_id = p_user_id
      and make_date(sheet.year, sheet.month + 1, 1) + (leave_item.ordinality::integer - 1) >= v_as_of_date
      and extract(month from make_date(sheet.year, sheet.month + 1, 1) + (leave_item.ordinality::integer - 1))::integer = sheet.month + 1
  ), covered_dates as (
    select vacation_date, is_vacation, is_holiday
    from calendar_dates
    where is_vacation or is_holiday
  ), grouped_dates as (
    select
      vacation_date,
      is_vacation,
      is_holiday,
      vacation_date - row_number() over (order by vacation_date)::integer as vacation_group
    from covered_dates
  ), vacation_blocks as (
    select
      min(vacation_date) filter (where is_vacation) as start_date,
      max(vacation_date) filter (where is_vacation) as end_date,
      count(*) filter (where is_vacation and not is_holiday)::integer as charged_days
    from grouped_dates
    group by vacation_group
  )
  select
    p_user_id,
    block.start_date,
    block.end_date,
    block.charged_days,
    'planned',
    now(),
    now()
  from vacation_blocks block
  where block.start_date is not null
    and block.end_date >= v_today
    and block.charged_days > 0;
end;
$$;

create or replace function public.track_timesheet_vacation_balance()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  if tg_op = 'DELETE' then
    perform public.sync_user_vacation_balance_events(old.user_id);
    return old;
  end if;

  perform public.sync_user_vacation_balance_events(new.user_id);
  return new;
end;
$$;

drop trigger if exists trg_track_timesheet_vacation_balance on public.timesheets;
create trigger trg_track_timesheet_vacation_balance
after insert or update or delete on public.timesheets
for each row execute function public.track_timesheet_vacation_balance();

create or replace function public.get_my_vacation_balance()
returns public.vacation_balance_snapshots
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_row public.vacation_balance_snapshots;
begin
  if auth.uid() is null then raise exception 'NO_SESSION'; end if;
  perform public.finalize_due_vacation_balance_events(auth.uid());
  select snapshot.* into v_row
  from public.vacation_balance_snapshots snapshot
  where snapshot.user_id = auth.uid();
  return v_row;
end;
$$;

create or replace function public.save_my_vacation_balance(
  p_balance_days numeric,
  p_annual_days numeric default 28
)
returns public.vacation_balance_snapshots
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_row public.vacation_balance_snapshots;
begin
  if auth.uid() is null then raise exception 'NO_SESSION'; end if;
  if p_balance_days is null or p_balance_days < 0 or p_balance_days > 999 then
    raise exception 'INVALID_VACATION_BALANCE';
  end if;
  if p_annual_days is null or p_annual_days < 1 or p_annual_days > 365 then
    raise exception 'INVALID_ANNUAL_VACATION_DAYS';
  end if;

  delete from public.vacation_balance_events where user_id = auth.uid();

  insert into public.vacation_balance_snapshots (user_id, balance_days, annual_days, as_of_date, updated_at)
  values (auth.uid(), round(p_balance_days, 2), round(p_annual_days, 2), timezone('Europe/Moscow', now())::date, now())
  on conflict (user_id) do update set
    balance_days = excluded.balance_days,
    annual_days = excluded.annual_days,
    as_of_date = excluded.as_of_date,
    updated_at = excluded.updated_at
  returning * into v_row;

  perform public.sync_user_vacation_balance_events(auth.uid());
  return v_row;
end;
$$;

revoke all on function public.finalize_due_vacation_balance_events(uuid) from public, anon, authenticated;
revoke all on function public.sync_user_vacation_balance_events(uuid) from public, anon, authenticated;
revoke all on function public.track_timesheet_vacation_balance() from public, anon, authenticated;
revoke all on function public.get_my_vacation_balance() from public, anon;
revoke all on function public.save_my_vacation_balance(numeric, numeric) from public, anon;
grant execute on function public.get_my_vacation_balance() to authenticated;
grant execute on function public.save_my_vacation_balance(numeric, numeric) to authenticated;

comment on table public.vacation_balance_events is
  'Planned paid leave blocks and irreversible deductions finalized after their end date.';

do $$
declare
  v_user_id uuid;
begin
  for v_user_id in select user_id from public.vacation_balance_snapshots loop
    perform public.sync_user_vacation_balance_events(v_user_id);
  end loop;
end $$;

commit;

do $$
declare
  v_job_id bigint;
begin
  if to_regprocedure('cron.schedule(text,text,text)') is null then return; end if;

  for v_job_id in
    select jobid from cron.job where jobname = 'alvisa-finalize-vacation-balances'
  loop
    perform cron.unschedule(v_job_id);
  end loop;

  perform cron.schedule(
    'alvisa-finalize-vacation-balances',
    '10 21 * * *',
    $cron$select public.finalize_due_vacation_balance_events();$cron$
  );
end $$;
